(load "auctex.el" nil t t)
(load "preview-latex.el" nil t t)

(setq TeX-auto-save t)
(setq TeX-parse-self t)
(setq TeX-PDF-mode t)
(defun texstuffs()
    (require 'preview-latex)
    (require 'preview)
    (set-face-background 'preview-reference-face "light gray")
    (set-face-foreground 'preview-reference-face "black")
  )
;; (add-hook 'TeX-mode-hook 'texstuffs)
(add-hook 'LaTeX-mode-hook 'texstuffs)
